/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gmself_mg_a7zip_Zip7Utils */

#ifndef _Included_com_gmself_mg_a7zip_Zip7Utils
#define _Included_com_gmself_mg_a7zip_Zip7Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gmself_mg_a7zip_Zip7Utils
 * Method:    excuteCommand
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmself_mg_a7zip_Zip7Utils_excuteCommand
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
