/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_syc_lalala_external_support_transmission_TransHandler */

#ifndef _Included_com_syc_lalala_externalSupport_transmission_TransHandler
#define _Included_com_syc_lalala_externalSupport_transmission_TransHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_syc_lalala_external_support_transmission_TransHandler
 * Method:    transmain
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_syc_lalala_externalSupport_transmission_TransHandler_transmain
  (JNIEnv *, jclass);

/*
 * Class:     com_syc_lalala_external_support_transmission_TransHandler
 * Method:    torrentAdd
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_syc_lalala_externalSupport_transmission_TransHandler_torrentAdd
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_syc_lalala_external_support_transmission_TransHandler
 * Method:    torrentAddByURL
 * Signature: (Ljava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_com_syc_lalala_externalSupport_transmission_TransHandler_torrentAddByURL
  (JNIEnv *, jclass, jstring, jintArray);

/*
 * Class:     com_syc_lalala_external_support_transmission_TransHandler
 * Method:    deleteAtask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_syc_lalala_externalSupport_transmission_TransHandler_deleteAtask
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_syc_lalala_external_support_transmission_TransHandler
 * Method:    pauseAtask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_syc_lalala_externalSupport_transmission_TransHandler_pauseAtask
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_syc_lalala_external_support_transmission_TransHandler
 * Method:    reStartAtask
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_syc_lalala_externalSupport_transmission_TransHandler_reStartAtask
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_syc_lalala_external_support_transmission_TransHandler
 * Method:    sessionDownloadSpeedLimit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_syc_lalala_externalSupport_transmission_TransHandler_sessionDownloadSpeedLimit
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_syc_lalala_external_support_transmission_TransHandler
 * Method:    torrentDownloadSpeedLimit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_syc_lalala_externalSupport_transmission_TransHandler_torrentDownloadSpeedLimit
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_syc_lalala_external_support_transmission_TransHandler
 * Method:    transClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_syc_lalala_externalSupport_transmission_TransHandler_transClose
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
